packaging_format = 2

id = "tooljet"
name = "ToolJet"
description.en = "Framework for building React-based Web applications and internal tools"
description.fr = "Construction d'applications Web basées sur React et d'outils internes"
version = "2.63.0~ynh2"

maintainers = ["Tagadda"]

[upstream]
license = "AGPL-3.0"
website = "https://tooljet.com/"
userdoc = "https://docs.tooljet.com/docs/intro"
code = "https://github.com/ToolJet/ToolJet"
cpe = "cpe:2.3:a:tooljet:tooljet"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "3G"
ram.build = "3G"
ram.runtime = "300M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/ToolJet/ToolJet/archive/refs/tags/v2.63.0.tar.gz"
        sha256 = "6292a51018dde0281e1781d584758bd3ff6bf63a4563ab553a441e37f3dbe9a6"

        autoupdate.strategy = "latest_github_release"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = "postgresql, postgresql-contrib, build-essential, xxd"

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "18.18.2"

