packaging_format = 2

id = "tooljet"
name = "ToolJet"
description.en = "Open-source low-code framework for building React-based web applications and internal tools"

version = "2.16.1~ynh1"

maintainers = ["Tagadda"]

[upstream]
license = "AGPL-3.0"
website = "https://tooljet.com/"
userdoc = "https://docs.tooljet.com/docs/intro"
code = "https://github.com/ToolJet/ToolJet"
cpe = "cpe:2.3:a:tooljet:tooljet"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/ToolJet/ToolJet/archive/v2.16.1.tar.gz"
        sha256 = "f3ba9112ba4afeabeda451ce302afb3fa431ba7f030702cc67457c37bc104a9f"

        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = "postgresql, postgresql-contrib, libpq-dev"

    [resources.database]
    type = "postgresql"
